# 服务配置
server:
  port: 9090
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    # tomcat 的uri编码
    uri-encoding: utf-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # tomcat 启动初始化线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.mds: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# 系统配置
# mds.goods.message.url
# 查看留言状况地址
mds:
  systemName: 小主平台
  version: 2.0
  filePath: F:/xiaozhu/file
  goods:
    message:
      url: http://127.0.0.1:8080/goods/info?goodsId=

